### ISSUE TITLE
bcftools command not found

### ISSUE THREAD

**Issue by hzz0024** [JimWhiting91/genotype_plot#7] opened 2020-12-04 14:19 UTC
It is a wonderful tool and thanks for posting this. However, when I run the example code, it shows an error message below,

sh: bcftools: command not found
Error in if (substr(vcf, start = 1, stop = 17) != "##fileformat=VCFv") { :

I then install the bcftools on my Mac OS but still see the error message, any ideas?

Thanks.
HG

**Comment by JimWhiting91** [comment] 2020-12-04 14:35
Hmm weird.

I think you're right in assuming that `sh: bcftools: command not found` is telling you you don't have bcftools installed, but this should have been resolved by installing it. Is the installation definitely working as expected and is bcftools in your path?

If you just try and run `bcftools query -l your.vcf` in terminal do you have any problems?

**Comment by hzz0024** [comment] 2020-12-04 16:21
Thanks for your quick reply. The installation is fine without error message. I put bcftools path in my global environment. It could be executed by typing _bcftools_ directly in the terminal. For example, 

$ bcftools query -l test.vcf | head -n 5
HG00096
HG00097
HG00099
HG00100
HG00101

**Comment by JimWhiting91** [comment] 2020-12-04 16:36
Ok thanks, so if its in the global path we should be alright. So the specific code that subsets and reads in the VCF is:
```
  # Subset the VCF on the command-line for the chr of interest
  vcf_tempfile <- tempfile(pattern = "gt_plot", fileext = '.vcf')
  on.exit({ unlink(vcf_tempfile) })
  if(tools::file_ext(vcf) == "gz"){
    system(glue::glue("bcftools view -r {chr}:{start}-{end} {vcf} > {vcf_tempfile}"), wait=TRUE)
  } else {
    stop("VCF needs to be bgzipped")
  }

  # Read in the subsetted VCF
  vcf_in<-read.vcfR(vcf_tempfile)
```
You can try just running simplified versions of this section and try and manually do the subsetting and reading in to see if we can pin down exactly where the error is coming from. Something like:
```
# Subset manually, so pick a region eg. chr1:1-100
system("bcftools view -r chr1:1-100 /path/to/vcf > ~/test.vcf"), wait=TRUE)

# Read in the subsetted VCF
vcf_in<-read.vcfR("~/test.vcf")
```
If you're still getting the `sh: bcftools: command not found` error it may be that there's an issue with how your R is communicating with your PATH? In which case you could test this possibility by replacing `system("bcftools view -r chr1:1-100 /path/to/vcf > ~/test.vcf"), wait=TRUE)` with `system("/path/to/bcftools view -r chr1:1-100 /path/to/vcf > ~/test.vcf"), wait=TRUE)` and see whether providing the full path to bcftools resolves it.

I'm not sure whether `Error in if (substr(vcf, start = 1, stop = 17) != "##fileformat=VCFv")` is reflecting a problem with the VCF not being made in the first instance due to the prior bcftools issue, or whether its trying to read in something that might be malformed?

So I'd give that a go and see if its any clearer exactly where the problem is taking place.

Cheers,
Jim

**Comment by hzz0024** [comment] 2020-12-20 02:29
Hi Jim, 

Thank you so much for the suggestion. I have successfully ran through the pipeline. For anyone who has the same issue, a simple solution is to add the bcftools path to the genotype_plot.R and reinstall the package. 

For example, at line 37 replace the 
```R
system(glue::glue("bcftools view -r {chr}:{start}-{end} {vcf} > {vcf_tempfile}"), wait=TRUE)
```
with 
```R
system(glue::glue("/PATH/TO/BCFTOOLS/bcftools view -r {chr}:{start}-{end} {vcf} > {vcf_tempfile}"), wait=TRUE)
```
Again, thanks for this package.

Best,
HG

**Closed as completed** 2020-12-20 02:29 UTC
