### ISSUE TITLE
Plot Appearance 

### ISSUE THREAD

**Issue by cassondranewman** [JimWhiting91/genotype_plot#10] opened 2021-04-26 14:00 UTC
Hello, 
Thank you for developing this wonderful tool! I have two questions regarding the plots I have been generating: 

A) Regardless of changing width and height, the y-axis labels are not lining up with the appropriate row. In the attached pdf you can see that the first two labels are collapsed and there are rows where there is no label present. How can I fix this?

B) When I have visualized this same vcf in IGV I can see data for all 94 samples. However when I plot the same file here in GenotypePlot there is a great deal of missing individuals. I know that there are filters applied on a variant-site basis, but are there filters being applied on the individual level (removing full individuals from what is plotted)? 

Thanks!
[EX1_3000000.pdf](https://github.com/JimWhiting91/genotype_plot/files/6377628/EX1_3000000.pdf)

**Comment by JimWhiting91** [comment] 2021-04-26 14:13
Hi Cassondra,

Thanks for flagging this, it certainly looks like there are a few things not working here. The issue with the two top labels collapsing was something I was aware in an earlier release, but I thought should have been resolved a while back, so if you are using the latest release then I'm not sure.

The issue with the whole empty rows is an interesting one as well, and not something I've seen when running this myself.

It would almost certainly be easiest if you could please send over a subset of your VCF (maybe the first 10 SNPs from this plot), so that I can try and recreate the errors my end and look into them. You can either upload that here or email it to me if you'd rather not share it here.

Cheers!
Jim

**Comment by cassondranewman** [comment] 2021-04-26 14:16
I will send an email over shortly! Thank you

**Comment by JimWhiting91** [comment] 2021-05-05 17:57
Hi Cassondra,

As I mentioned over email, these two problems were caused by two separate bugs that should now be resolved. I'll describe them here for anyone that comes across a similar issue:

_Regardless of changing width and height, the y-axis labels are not lining up with the appropriate row. In the attached pdf you can see that the first two labels are collapsed and there are rows where there is no label present. How can I fix this?_
**>>> So the problem here with the first 2 rows being collapsed was the same issue I was having before, however the if statement I’d used to try and catch this and resolve it wasn’t working properly, so this is now resolved hopefully. The next issue involving empty rows was partly a bug and partly expected behaviour. So in your popmap, you have 92 populations and 94 individuals, so there are 2 cases in which a single population contains 2 individuals. Based on the popmap, these 2 individuals will be grouped into a single-labelled population with 2 rows which is what was happening. The label for these is supposed to be centred, however it was being rounded down to an integer value which gave the impression of an empty row. Again I think I’ve resolved this now.**

_When I have visualized this same vcf in IGV I can see data for all 94 samples. However when I plot the same file here in GenotypePlot there is a great deal of missing individuals. I know that there are filters applied on a variant-site basis, but are there filters being applied on the individual level (removing full individuals from what is plotted)?_
**>>> This was a little trickier to find but the bug here was due to all your individuals being named as numbers 1-94. This isn’t something I’d considered, and there is a point at which individual names are converted to y-axis positions using a find/replace loop. With the names already as numbers however, rows were being overwritten prior to plotting which created all your empty rows. I’ve tweaked it so this shouldn’t happen anymore, but definitely good to have this caught this bug!**

The new update should resolve your plotting issues, so I'll close this issue. However if you continue to have problems we can open it up again!

Cheers,
Jim

**Closed as completed by JimWhiting91** 2021-05-05 17:57 UTC
